### ISSUE TITLE
no DICOM files found with Files Manager 20.2.2a

### ISSUE THREAD

**Issue by AdrienRobin** [nifm-gin/MP3#20]
Hello, 
I'm having some troubles opening our DICOM (.dcm) sequences from the Files Manager. When the folder is selected from the Dicom button, the program indicates "no Dicom file found" in the Format section.
I am working on Windows 10, Matlab R2019a, Files Manager 20.2.2a

**Comment by brosscle** [comment]
Hi !
Have you tried to select the parent folder ? Actually the best thing to do is to select the folder containing the DICOMDIR file that summarizes your data. When this DICOMDIR file is missing, trying to select the folder parent of the one containing your sequences might solve the issue. If it still doesn't work, and if you are allowed to, please send us one sample of your data to check if there is a bug that prevents the MRIFileManager to correctly convert your DICOM in nifti.
Thanks !
Clément

**Comment by blemasso** [comment]
Hi Adrien,

We are currently updating our loader/converter in order to handle your dcm files.
So far, we still have issues with somes conversions.
do you need to work with all these scans in MP3? Or is it possible to focus our development on certain scans?

than you,
Benjamin

**Comment by AdrienRobin** [comment]
Hello,
Thank you for your answers and to try updating your loader.
We would like to be able to treat the calf scans as a priority, those corresponding to the brain scans will be treated by another team.
Let me know if you need further information from my side
Adrien

**Comment by blemasso** [comment]
Ok, good to know!

We are updating our loader and so far we can import the following scans :
--> t1_tse_dixon_tra
--> t1_tse_dixon_tra_t1_tse_dixon_tra_F
--> t1_tse_dixon_tra_t1_tse_dixon_tra_W

we are still working on this ones.
Could you tell us, if you want to work on all of them or only some of them?
--> t1_mprage_sag_p2_isp
--> T2_STIR_COR_ORBITES
--> t2_swi_tra_p2_SWI_Image(SW)
--> t2_space_sag_p2_iso
--> t2_swi_tra_p2_Pha_Image
--> t2_swi_tra_p2_SWI_Image
--> FL_3D_TRA_GADO_FL_3D_TRA_GADO_SUB

Since the followings scans are not raw images but reconstructed images (3D render..) we will not able to load them
--> antio_twist_sag_iso_SUB_MIP_COR
--> MIP_ROULE

**Comment by montigno** [comment]
Hello,

I think I solved the problem, now all images (except angio, but that's normal) register well with spm and MP3..

The problem was with the slice thickness, some dicom showed strange value.
I had to calculate this thickness myself with the image positions.

I'm still doing tests on other DIcoms and if all goes well, I'll push it on Github.

Olivier

**Comment by montigno** [comment]
I pushed a new version on 'dev' branch.

Can you inform me if it's all for you ?


Thanks !

**Comment by blemasso** [comment]
It works well on my side, thank you Olivier!

to resume, we can load correctly every scans except:
--> angio_twist_sag_iso_SUB_MIP_COR
--> FL_3D_TRA_GADO_FL_3D_TRA_GADO_SUB_MIP_COR
--> MIP_ROULE

@AdrienRobin, could you tell us if its OK on your side using last version of the 'dev' branch 
[c8534ad](https://github.com/nifm-gin/MP3/commit/c8534adcab568481549780fa6c35e62ab95ebcc4)

**Comment by AdrienRobin** [comment]
Hello,
I downloaded the new version but the file manager still refuses to open my files.
However, when I save them back to DICOM format after opening them with a dicom viewer (RadiAnt), the file manager is now able to recognize them in the folder and open them.
I'm still doing some testing but now it seems to works pretty well. Thank you for your time and efforts to improve your program!
I will come back to you if I encounter other problems. Many thanks again
