### ISSUE TITLE
Use a constant as BVf input in the SO2 module

### ISSUE THREAD

**Issue by GaetanDavout** [nifm-gin/MP3#7]
**Is your feature request related to a problem? Please describe.**
In PET oxygen analysis, sometimes a constant is used instead of a BVf map to calculate CMRO2 map. In order to compare both, it would be useful to do the same for MRI.

**Describe the solution you'd like**
Add an option to chose one of the options we want as input. i.e. either map or constant.

**Describe alternatives you've considered**
Add another module with a constant map as output.

**Additional context**

**Comment by blemasso** [comment]
Could you precise which module you would like to modify?
The SO2 or the CMRO2?

**Comment by GaetanDavout** [comment]
the SO2 module (as BVf is one of its input).
thank you!

**Comment by brosscle** [comment]
Hi Gaetan !
Please find in your mailbox the file Module_SO2_Comparison_PET that takes as input a R2Prim map and a constant in order to replace the BVf.
Since we believe this function will not be often used, we decided to not put it on the git repository.
We also preferred to create a new module rather than modify the initial SO2 module in order to keep it clean for the other users.
Now you just have to drag & drop this .m file into the folder MP3_pipeline/Modules_Repository/ of your MP3 source code to be allowed to enjoy the module in the pipeline manager.
Feel free to report any issue !
Good afternoon,
Clément

**Comment by brosscle** [comment]
And please close this issue if the answer suits you :)

**Comment by GaetanDavout** [comment]
It suits me, thanks a lot!
